[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gcmc"
version = "0.9.0"
description = "MC simulations for solid and adsorbate systems"
authors = [
    { name="Wei Chen", email="wei.chen@uclouvain.be" }
]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}

dependencies = [
    "ase",
    "scipy",
    "networkx",
    "matplotlib",
    "mace-torch",
    "PyYAML",
]

[project.optional-dependencies]
speedups = [
    "matscipy"
]
active-learning = [
    "dscribe",
    "h5py",
    "pymatgen",
]

[project.urls]
Homepage = "https://github.com/wch3n/gcmc"

[project.scripts]
gcmc-oer-workflow = "reaction.cli:main"
gcmc-reference-thermo = "reaction.reference_thermo:main"
gcmc-run-alloy-cmc = "gcmc.run_alloy_cmc:main"
gcmc-run-alloy-pt = "gcmc.run_alloy_pt:main"
gcmc-run-alloy-pt-ray = "gcmc.run_alloy_pt:main"
gcmc-run-adsorbate-cmc = "gcmc.run_adsorbate_cmc:main"
gcmc-run-adsorbate-pt = "gcmc.run_adsorbate_pt:main"
gcmc-run-adsorbate-gcmc = "gcmc.run_adsorbate_gcmc:main"
gcmc-run-adsorbate-gcmc-scan = "gcmc.run_adsorbate_gcmc_scan:main"
gcmc-prepare-adsorbate-cmc = "gcmc.prepare_adsorbate_cmc_inputs:main"
gcmc-active-learning-select = "tools.active_learning.selection:main"
gcmc-active-learning-evaluate = "tools.active_learning.evaluation:main"

[tool.setuptools.packages.find]
include = ["gcmc*", "reaction*", "tools*"]
